name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-2019, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libwayland-cursor0 libxkbcommon-dev libwayland-dev
      
    - name: Build
      run: cargo build --features ci
    - name: Run tests
      run: cargo test --features ci
    
    - name: Install Clippy
      run: rustup component add clippy
      
    - name: Run Clippy
      run: cargo clippy --features ci
      
    - name: Install rustfmt
      run: rustup component add rustfmt
      
    - name: Check formatting
      run: cargo fmt -- --check
